"""v3.5: workflow templates — user-authored, parameterized task recipes.

A template is the human-authored precursor to v4's skill registry: a reusable
recipe the user writes by hand (name, parameters, an instruction template, and
the v3 knobs — caste, target repo, network allowlist, env allowlist, budget).
The Queen *instantiates* a template with concrete parameters and mints a
**completely normal** ``CodingWorkerTask`` from it — a filled-in template is just
a regular task, so this requires **zero contract change** (the instance feeds the
same ``run_task`` / ``mint_task`` path as any manual run).

Deliberately small (decision record: v3.5 = "workflow templates, user-authored —
no learning loop, no promotion pipeline; that is v4"). Parameters substitute into
the instruction template via ``{{name}}`` placeholders — double-brace so a literal
``$VAR`` in the instructions (shell snippets, env refs) never collides.
"""

from __future__ import annotations

import json
import re
import tomllib
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from skep.worker_contract import KNOWN_WORKER_KINDS, Budget, Permissions

from .contracts_io import DEFAULT_BUDGET

# ``{{ name }}`` with optional inner whitespace; double-brace to avoid colliding
# with a literal ``$VAR`` or ``{...}`` in instructions handed to a coding worker.
_PLACEHOLDER = re.compile(r"\{\{\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*\}\}")


class TemplateError(ValueError):
    """An authoring or instantiation error, surfaced with a doctor-style message."""


@dataclass(frozen=True)
class TemplateParam:
    """One named parameter. Required unless it declares a ``default``."""

    name: str
    description: str = ""
    default: str | None = None

    @property
    def required(self) -> bool:
        return self.default is None


@dataclass(frozen=True)
class WorkflowTemplate:
    """A reusable, parameterized task recipe (the v3 knobs + an instruction template).

    ``repo``/``ref`` are an *optional* default target — a template can pin a repo,
    or leave it for the caller to supply at instantiation. Everything else is the
    fixed recipe; only the parameters vary per run.
    """

    name: str
    instructions: str
    description: str = ""
    worker_kind: str = "coding"
    params: tuple[TemplateParam, ...] = ()
    repo: str | None = None
    ref: str | None = None
    network: tuple[str, ...] = ()
    env_allowlist: tuple[str, ...] = ()
    shell_allowlist: tuple[tuple[str, ...], ...] = ()
    allow_git_mutation: bool = False
    wall_clock_seconds: int = DEFAULT_BUDGET.wall_clock_seconds
    max_iterations: int = DEFAULT_BUDGET.max_iterations
    max_actions: int = DEFAULT_BUDGET.max_actions
    max_provider_calls: int = DEFAULT_BUDGET.max_provider_calls
    created_at: str = ""
    # v4: where this template came from — ``"user"`` (hand-authored, v3.5) or
    # ``"learned"`` (generated by the skill generalizer and human-approved into the
    # registry). The unified registry runs/schedules both identically; provenance is
    # a tag, never a behavioural branch. Defaults to ``"user"`` so every v3.5
    # construction site stays correct.
    provenance: str = "user"


@dataclass(frozen=True)
class TemplateInstance:
    """The result of filling a template — the exact arguments ``run_task`` needs.

    These are ordinary task arguments; ``run_task`` mints a normal
    ``CodingWorkerTask`` from them. Nothing here is template-specific downstream.
    """

    instructions: str
    worker_kind: str
    repo: str
    ref: str | None
    permissions: Permissions
    budget: Budget
    params: Mapping[str, str] = field(default_factory=dict)


def placeholder_names(text: str) -> set[str]:
    return set(_PLACEHOLDER.findall(text))


def substitute(text: str, values: Mapping[str, str]) -> str:
    def _replace(match: re.Match[str]) -> str:
        name = match.group(1)
        if name not in values:
            raise TemplateError(f"no value for placeholder {{{{{name}}}}}")
        return values[name]

    return _PLACEHOLDER.sub(_replace, text)


def validate_template(template: WorkflowTemplate) -> None:
    """Check a template is internally consistent (authoring-time validation)."""
    if not template.name:
        raise TemplateError("template name is required")
    if not template.instructions:
        raise TemplateError(f"template {template.name!r}: instructions are required")
    if template.worker_kind not in KNOWN_WORKER_KINDS:
        known = ", ".join(repr(k) for k in KNOWN_WORKER_KINDS)
        raise TemplateError(
            f"template {template.name!r}: unknown worker_kind {template.worker_kind!r}; "
            f"the contract supports {known}"
        )
    seen: set[str] = set()
    for param in template.params:
        if param.name in seen:
            raise TemplateError(f"template {template.name!r}: duplicate parameter {param.name!r}")
        seen.add(param.name)
    undeclared = placeholder_names(template.instructions) - seen
    if undeclared:
        names = ", ".join(sorted(undeclared))
        raise TemplateError(
            f"template {template.name!r}: instructions reference undeclared parameter(s) "
            f"{{{{{names}}}}}; declare them under params or fix the names"
        )


def resolve_params(template: WorkflowTemplate, params: Mapping[str, str]) -> dict[str, str]:
    """Overlay provided params on declared defaults; reject unknown / missing-required."""
    declared = {p.name: p for p in template.params}
    unknown = set(params) - set(declared)
    if unknown:
        names = ", ".join(sorted(unknown))
        accepted = ", ".join(sorted(declared)) or "(none)"
        raise TemplateError(
            f"template {template.name!r}: unknown parameter(s) {names}; "
            f"this template declares {accepted}"
        )
    resolved: dict[str, str] = {}
    missing: list[str] = []
    for name, param in declared.items():
        if name in params:
            resolved[name] = params[name]
        elif param.default is not None:
            resolved[name] = param.default
        else:
            missing.append(name)
    if missing:
        names = ", ".join(sorted(missing))
        raise TemplateError(
            f"template {template.name!r}: missing required parameter(s) {names} "
            f"(pass --param NAME=VALUE)"
        )
    return resolved


def instantiate(
    template: WorkflowTemplate,
    params: Mapping[str, str] | None = None,
    *,
    repo: str | None = None,
    ref: str | None = None,
) -> TemplateInstance:
    """Fill a template with concrete parameters → the arguments for a normal task.

    ``repo``/``ref`` override the template's defaults (the target a schedule or
    ``run`` aims at). Raises ``TemplateError`` if the template is inconsistent,
    a required parameter is missing, an unknown one is passed, or no repo resolves.
    """
    validate_template(template)
    values = resolve_params(template, params or {})
    instructions = substitute(template.instructions, values)
    target_repo = repo if repo is not None else template.repo
    if not target_repo:
        raise TemplateError(
            f"template {template.name!r}: no target repo — pin one in the template "
            "or pass a repo when instantiating"
        )
    permissions = Permissions(
        read=["workspace"],
        write=["workspace"],
        network=list(template.network),
        env_allowlist=list(template.env_allowlist),
        shell_allowlist=[list(command) for command in template.shell_allowlist],
        allow_git_mutation=template.allow_git_mutation,
    )
    budget = Budget(
        wall_clock_seconds=template.wall_clock_seconds,
        max_iterations=template.max_iterations,
        max_actions=template.max_actions,
        max_provider_calls=template.max_provider_calls,
    )
    return TemplateInstance(
        instructions=instructions,
        worker_kind=template.worker_kind,
        repo=str(target_repo),
        ref=ref if ref is not None else template.ref,
        permissions=permissions,
        budget=budget,
        params=values,
    )


def template_from_dict(data: Mapping[str, Any]) -> WorkflowTemplate:
    """Build a template from a parsed file/dict (file authoring). Validated."""
    if "name" not in data:
        raise TemplateError("template file: 'name' is required")
    if "instructions" not in data:
        raise TemplateError("template file: 'instructions' is required")
    raw_params = data.get("params", [])
    if not isinstance(raw_params, list):
        raise TemplateError(
            "template file: 'params' must be a list of {name, description?, default?}"
        )
    params = tuple(
        TemplateParam(
            name=str(p["name"]),
            description=str(p.get("description", "")),
            default=None if p.get("default") is None else str(p.get("default")),
        )
        for p in raw_params
    )
    budget = data.get("budget", {})
    template = WorkflowTemplate(
        name=str(data["name"]),
        instructions=str(data["instructions"]),
        description=str(data.get("description", "")),
        worker_kind=str(data.get("worker_kind", "coding")),
        provenance=str(data.get("provenance", "user")),
        params=params,
        repo=None if data.get("repo") is None else str(data["repo"]),
        ref=None if data.get("ref") is None else str(data["ref"]),
        network=tuple(str(d) for d in data.get("network", [])),
        env_allowlist=tuple(str(e) for e in data.get("env_allowlist", [])),
        shell_allowlist=_command_matrix(data.get("shell_allowlist", []), "shell_allowlist"),
        allow_git_mutation=_bool_field(data.get("allow_git_mutation", False), "allow_git_mutation"),
        wall_clock_seconds=int(budget.get("wall_clock_seconds", DEFAULT_BUDGET.wall_clock_seconds)),
        max_iterations=int(budget.get("max_iterations", DEFAULT_BUDGET.max_iterations)),
        max_actions=int(budget.get("max_actions", DEFAULT_BUDGET.max_actions)),
        max_provider_calls=int(budget.get("max_provider_calls", DEFAULT_BUDGET.max_provider_calls)),
    )
    validate_template(template)
    return template


def _command_matrix(raw: object, field: str) -> tuple[tuple[str, ...], ...]:
    if not isinstance(raw, list):
        raise TemplateError(f"template file: {field!r} must be a list of command argv lists")
    commands: list[tuple[str, ...]] = []
    for item in raw:
        if not isinstance(item, list) or not item:
            raise TemplateError(f"template file: {field!r} entries must be non-empty lists")
        commands.append(tuple(str(part) for part in item))
    return tuple(commands)


def _bool_field(raw: object, field: str) -> bool:
    if not isinstance(raw, bool):
        raise TemplateError(f"template file: {field!r} must be true or false")
    return raw


def load_template_file(path: Path) -> WorkflowTemplate:
    """Author a template from a ``.toml`` or ``.json`` file (human-authored)."""
    text = path.read_text(encoding="utf-8")
    if path.suffix == ".toml":
        data = tomllib.loads(text)
    elif path.suffix == ".json":
        data = json.loads(text)
    else:
        raise TemplateError(f"template file must be .toml or .json, got {path.suffix!r}")
    return template_from_dict(data)


def template_to_dict(template: WorkflowTemplate) -> dict[str, Any]:
    """Serialize a template back to a plain dict (for ``show`` and round-tripping)."""
    return {
        "name": template.name,
        "description": template.description,
        "worker_kind": template.worker_kind,
        "provenance": template.provenance,
        "instructions": template.instructions,
        "repo": template.repo,
        "ref": template.ref,
        "network": list(template.network),
        "env_allowlist": list(template.env_allowlist),
        "shell_allowlist": [list(command) for command in template.shell_allowlist],
        "allow_git_mutation": template.allow_git_mutation,
        "budget": {
            "wall_clock_seconds": template.wall_clock_seconds,
            "max_iterations": template.max_iterations,
            "max_actions": template.max_actions,
            "max_provider_calls": template.max_provider_calls,
        },
        "params": [
            {"name": p.name, "description": p.description, "default": p.default}
            for p in template.params
        ],
    }


# -- v17 Step 4: deep research template --------------------------------------

# Depth/format are constrained to a small set so a research run can't be steered
# into arbitrary behaviour through a free-text param.
RESEARCH_DEPTHS: tuple[str, ...] = ("shallow", "standard", "deep")
RESEARCH_OUTPUT_FORMATS: tuple[str, ...] = ("markdown", "html")


def deep_research_template(
    source_allowlist: Sequence[str], *, created_at: str = ""
) -> WorkflowTemplate:
    """A governed deep-research template: a *worker run* (never Queen-side
    browsing) that reads only allow-listed sources and produces file report
    artifacts. The source allowlist becomes the run's D1 network allowlist, so
    egress is pinned to the filtering proxy on BOTH backends (v28 closed the
    Linux gap); a source off the allowlist is a supervisor approval, never a
    silent fetch."""
    return WorkflowTemplate(
        name="deep-research",
        description=(
            "Governed deep research: read only allow-listed sources and write a "
            "cited report as file artifacts."
        ),
        worker_kind="researcher",
        instructions=(
            "Research this question and write a cited report.\n"
            "Question: {{question}}\n"
            "Depth: {{depth}}\n"
            "Output format: {{output_format}}\n"
            "Sources: {{sources}}\n"
            "Sources are the listed URLs (or, when none are listed, the "
            "allow-listed hosts); each is fetched as readable text and cited in "
            "the report with evidence. Hosts off the allowlist are refused, "
            "never fetched."
        ),
        params=(
            TemplateParam(name="question", description="the research question"),
            TemplateParam(
                name="depth", description="shallow|standard|deep", default="standard"
            ),
            TemplateParam(
                name="output_format", description="markdown|html", default="markdown"
            ),
            TemplateParam(
                name="sources",
                description="space-separated seed URLs to read (v46-F1)",
                default="",
            ),
        ),
        network=tuple(source_allowlist),
        created_at=created_at,
    )
